#  installing NGNIX

- name: "Install nginx via apt"
  ansible.builtin.apt:
    name: "nginx"
    state: "latest"
    update_cache: true

- name: "Create folder"
  ansible.builtin.file:
    path: "/mnt/folder"
    state: directory

#  - name: "Delete folder"
#    ansible.builtin.file:
#      path: "/mnt/folder"
#      state: absent