
---
- hosts: "all"
  roles:
    - nginx
    - mysql
    - php

  tasks:
  - name: "Copy file to server"
    ansible.builtin.copy:
      src: "wordpress/files/upload_file.txt"
      dest: "/mnt/folder/"
#      owner: "testuser"
#      group: "testuser"
#      mode: "0644"